### ISSUE TITLE
Token detail page

### ISSUE THREAD

**Issue by tign227** [Novaro-Labs/novaro-web#18]
1，when click token page show token details
<img width="161" alt="截屏2024-10-26 09 59 12" src="https://github.com/user-attachments/assets/063b2e4e-1433-4c3e-ae81-5d853e858beb">

2,  mock data as api is not ready for now

3，UI token details
<img width="862" alt="截屏2024-10-26 10 01 56" src="https://github.com/user-attachments/assets/4a5d7348-345b-4539-8990-48d3ea6b5200">

**Comment by tign227** [comment]
token image storage: https://github.com/Novaro-Labs/novaro-server/issues/21

**Comment by deadpoolcnn** [comment]
done
