### ISSUE TITLE
Space with dNFT

### ISSUE THREAD

**Issue by tign227** [Novaro-Labs/novaro-web#27]

**Comment by tign227** [comment]
<img width="580" alt="截屏2024-11-22 20 33 17" src="https://github.com/user-attachments/assets/7a43677b-7230-4bd2-8d33-2557bca94d1a">

feed from Social Oracle every 24 hours
<img width="712" alt="截屏2024-11-22 20 33 40" src="https://github.com/user-attachments/assets/542b0003-22fd-4433-986b-09d7e0487cad">

**Comment by ningxzx** [comment]
done
