### ISSUE TITLE
Community:  adjust token section

### ISSUE THREAD

**Issue by tign227** [Novaro-Labs/novaro-web#35]
1, new layout 
<img width="873" alt="截屏2024-11-29 16 07 17" src="https://github.com/user-attachments/assets/32771219-58c4-46c7-9776-9964cdf6e7e8">

2, remove slogan
<img width="591" alt="截屏2024-11-29 16 10 28" src="https://github.com/user-attachments/assets/52db7cd6-16bc-49b8-a803-1500fd1f1315">

**Comment by GuanWhite** [comment]
I have completed tasks 1 and 2 locally, and the rendering is shown below：
![new layout](https://github.com/user-attachments/assets/834d86d6-207e-497d-aaaa-0643b49ebbb2)
![remove slogan](https://github.com/user-attachments/assets/44adb4e8-d002-43cb-bc7c-57f3428be296)
